Accounts/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name='Accounts'

urlpatterns = [
    path('home/', views.home, name='home'),
    path('login/', views.login, name='login'),
    path('instruction/', views.instruction, name='instruction'),
    path('authlogin/', views.authlogin, name='authlogin'),
    path('adminduty/', views.adminduty, name='adminduty'),
    path('answers/', views.studentlist, name='studentlist'),
    path('studentslist/', views.liststudents, name='liststudent'),
    path('addstudent/', views.addstudent, name='addstudent'),
    path('profile/', views.profile, name='profile'),
    #path('login/', views.loginspeak, name='logins'),
    
    

]

Drishti/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static
from Accounts import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('accounts/', include('Accounts.urls',namespace='account')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('exams/', include('exam.urls',namespace='exam')),

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

exam/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name='exam'

urlpatterns = [
   
    path('start/',views.exam,name='startexam'),
    path('finalresult/',views.finaloutput,name="finalresult"),
    path('addquestion/',views.createquestion,name='addquestion'),
    path('questionlist/',views.questionlist,name='questionlist'),  
    path('result/',views.result,name="result"),
  
    #path('final/',views.finalscore,name='finalscore'),
    path('about/',views.about,name='about'),
    path('completed/',views.thankyou,name='completed')
   # path('addquestion/',views.createquestion,name='addquestion')
   # path('speech/', views.hai, name='speech'),
    
    

]

templates/Adminduty.html
<html>
{% load static %}
<head>
<link href="{% static 'css/report/roboto.css' %}" rel="stylesheet" media="all" type="text/css">
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css/exams.css' %}">
<link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css" media="all" />
<link href="{% static 'css/style (2).css' %}" rel="stylesheet" type="text/css" media="all" />
<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" />
<style>
    .hello {
      width: 320px;
      padding: 100px;
      color:black;
      border: 5px solid ;
      margin: 200;
      background-color:rgb(112, 135, 156);
    }
    body
    {
        background-color: bisque;
    }
    </style>
</head>
<body>
    <h1><a class="navbar-brand" style="color:black" href="/"><b>Drishti</b></a></h1>

<div class="content">
        <div class="col-md-12 col-xs-offset-0">
<div class="row">

<a  href="{% url 'account:addstudent' %}">
<div class="col-xs-12 col-sm-2 col-md-3 hp-each-course">
<div class="inner" >

<div class="hello">
    
<h4><b>STUDENTS</b></h4>

</div>
</a>
</div>
</div>

  </div>
  </div>
 
  <a  href="{% url 'account:addstudent' %}">
    <div class="col-xs-12 col-sm-2 col-md-3 hp-each-course">
      <div class="inner" >
      <a  href="{% url 'exam:addquestion' %}">
      <div class="hello">
          
      <h4><b>QUESTION</b></h4>
      
      </div>
      </a>
      </div>
      </div>

    </div>
    </div>
       
  
</div>
</div>
</div>

</body>
</html>

templates/addstudent.html
{% load static %}
{% load bootstrap4 %}
<html>
    <head>
        <link href="{% static 'css/report/roboto.css' %}" rel="stylesheet" media="all" type="text/css">
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/exams.css' %}">
        <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css" media="all" />
        <link href="{% static 'css/style (2).css' %}" rel="stylesheet" type="text/css" media="all" />
        <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" />
        
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<style>
    .w3
    {
       
        margin-top: 70px;
    
       
      
    }
    
body
{
    background-image: url("{% static 'images/3705537.jpg' %}");
    background-size: 2000px 800px;
}
input[type=submit]
{
    background-color: #444d9e;
    border: none;
    color: white;
    padding: 16px 22px;
    text-decoration: none;
    margin: 4px 2px;
    cursor: pointer;
  
}
.previous {
    background-color: rgb(255, 81, 0);
    color: black;
  }
  
.round {
  border-radius: 50%;
}
a {
  text-decoration: none;
  display: inline-block;
  padding: 8px 16px;
}

</style>
</head>
<body>
    <a href="/" style="color:#454b53;text-decoration: none">
        <h1 style="border: 4px solid white;width:150px;padding:4px;color:white">D r i s h t i</h1>
        </a>
        <a href="{% url 'account:adminduty' %}" class="previous round" style="margin-left: 1200px;">&#8249;</a>
        <div class="row">
    
    <div class="container">
        <center><h1><b><u>REGISTER STUDENT</u></b></h1></center>
    <form method="POST" class="form"  enctype="multipart/form-data">
        <div class="w3">
    <table>
   
        {% csrf_token %}
        
       <tr>  {% bootstrap_form student %}</tr>
    
    </table>
</div>

</div>
<div class="form-group">
    <div class="col-6">                       
    <input type="submit" name="submit" style="width: 100px;margin-left:950px;margin-top:0px;" value="Register">
</div>
</div>
</div>

</form>
{% for i in messages %}
<script>
    alert('{{ i }}');
</script>
{% endfor %}
</div>
</body>

</html>

templates/answerlist.html

{% load static %}
{% load bootstrap4 %}
<!DOCTYPE html>
<html>
  <head>
    <link rel="shortcut icon" href="http://bit.ly/ghfavicon" width=32px>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate" />
  <meta http-equiv="Pragma" content="no-cache" />
  <meta http-equiv="Expires" content="0" />
  <title>exam started</title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link rel="stylesheet" href="style.css">
  <link href="https://fonts.googleapis.com/css?family=Shadows+Into+Light" rel="stylesheet">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
<title>Answers List</title>
<meta name="viewport" content="width=device-width, initial-scale=1">

<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<style>
  .div2 {
    margin-left: 250px;
    width: 1000px;
    height: 350px;  
    padding: 50px;
    border: 1px solid white;
    background-color: rgba(219, 225, 230, 0.856);
  }
  .c{
    margin-top: 150px;
    
  }
  .previous {
    background-color: rgb(255, 81, 0);
    color: black;
  }
  
.round {
  border-radius: 50%;
}
a {
  text-decoration: none;
  display: inline-block;
  padding: 8px 16px;
}

</style>
</head>
<body style="background-color:cadetblue">

<div class="w3-container">
  <a href="/" style="color:#454b53;text-decoration: none">
    <h1 style="border: 4px solid white;width:180px;padding:4px;color:white">D r i s h t i</h1>
    </a>
    <a href="{% url 'account:adminduty' %}" class="previous round" style="margin-left: 1200px;">&#8249;</a>
    {% if answer_list %}
    {% for i in answer_list %}
<h3></h3>
<div class="div2">
        <p style="background-color:rgb(34, 160, 209);width:60px;color:white">Ques :</p><br>
        <span class="w3-large"><b>? {{i.que}}</b></span><br>
        <p></p>
        <p style="background-color:rgb(23, 201, 23);width:60px;color:white">Answ :</p><br>
        <span>{{i.content}}</span><br>
     
  </div>
  {% endfor %}
  
  <form method="POST">
    {% csrf_token %}
    <center>
    <div class="c">
  <span>{{result}}<input type="submit" name="submit"style="background-color: tomato;color:white" value="SUBMIT"></span>
  * Each Question Carry 10 Marks
  
  </div>
  </center>
  {% for i in messages %}
<script>
    alert('{{ i }}');
</script>
{% endfor %}
  </form>
  
  {%  if answer_list.has_other_pages %}
  <ul class="pagination pagination-sm">
  {% if answer_list.has_previous %}
           <li><a href="?page={{ answer_list.previous_page_number }}">Prev</a></li>
      {% else %}
            <li class="disabled"></li>
      {% endif %}
  {% for pages in answer_list.paginator.page_range %}
      {% if answer_list.number == pages %}
             <li><a href="#">{{ pages }}</a></li>
      {% else %}
            <li><a href="?page={{pages}}">{{ pages }}</a></li>
      {% endif %}
  {% endfor %}
  {% if answer_list.has_next %}
          <li><a href="?page={{answer_list.next_page_number }}">Next</a></li>
      {% else %}
      <li><a href="{% url 'exam:result' %}">Click Here To Continue..</a></li>
      {% endif %}
      {% endif %}
</div>
{% else %}

<center>
  <img src="{% static 'images/search123.png' %}" height="142" width="142">
<p style="color:rgb(194, 33, 33);font-size:40px;margin-top:200px">{{details}}</p>
</center>
{% endif %}
</body>
</html>

templates/exam1.html

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
	<link rel="shortcut icon" href="http://bit.ly/ghfavicon" width=32px>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css" />
	<link rel="stylesheet" href="style.css">
	<link rel="prefetch" href="pause1.svg">
	<link rel="prefetch" href="play1.svg">
	<link rel="prefetch" href="stop1.svg">
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width,initial-scale=1.0">
	<script src="script.js" defer></script>
	<title>instructions</title>
</head>
<style type="text/css">
	@import url('https://fonts.googleapis.com/css?family=Crimson+Text');
article {
    width: 60%;
    margin: auto;
}
blockquote,
div,
h1 {
    text-align: center;
}
blockquote {
    font-size: 1.2rem;
}

button {
    background: none;
    border: none;
    cursor: pointer;
    height: 48px;
    outline: none;
    padding: 0;
    width: 48px;
}
html {
    font-size: 16pt;
    font-family: crimson text;
}
#play {
  background-image: url(https://rpsthecoder.github.io/js-speech-synthesis/play.svg);
}

#play.played {
  background-image: url(https://rpsthecoder.github.io/js-speech-synthesis/play1.svg);
}

#pause {
  background-image: url(https://rpsthecoder.github.io/js-speech-synthesis/pause.svg);
}

#pause.paused {
  background-image: url(https://rpsthecoder.github.io/js-speech-synthesis/pause1.svg);
}

#stop {
  background-image: url(https://rpsthecoder.github.io/js-speech-synthesis/stop.svg);
}

#stop.stopped {
  background-image: url(https://rpsthecoder.github.io/js-speech-synthesis/stop1.svg);
}
@media (max-width: 700px) {
    html {
        font-size: 14pt;
    }
    article {
        width: 90%;
    }
}

body {
  margin: 0;
}


/*  demo decor */

#-demo-title {
  position: fixed;
  top: 0;
  width: 100%;
  height: 36px;
  background-color: rgb(25, 26, 25);
  color: #0F316C;
  line-height: 36px;
  font-weight: bold;
  font-size: 36pt;
  text-align: center;
}

#-demo-profile {
  float: left;
  height: 100%;
  opacity: .4;
}

#-demo-profile:hover {
  opacity: 1;
}

@media (max-width: 400px) {
  #-demo-title {
      font-size: 12pt;
  }
}
hoverable{
display:inline-block;
backface-visibility: hidden;
vertical-align: middle;
position:relative;
box-shadow: 0 0 1px rgba(0,0,0,0);
tranform: translateZ(0);
transition-duration: .3s;
transition-property:transform;
}

.hoverable:before{
position:absolute;
pointer-events: none;
z-index:-1;
content: '';
top: 100%;
left: 5%;
height:10px;
width:90%;
opacity:0;
background: -webkit-radial-gradient(center, ellipse, rgba(255, 255, 255, 0.76) 0%, rgba(255, 255, 255, 0.836) 80%);
background: radial-gradient(ellipse at center, rgba(255, 255, 255, 0.884) 0%, rgba(3, 3, 3, 0.904) 80%);
/* W3C */
transition-duration: 0.3s;
transition-property: transform, opacity;
}

.hoverable:hover, .hoverable:active, .hoverable:focus{
transform: translateY(-5px);
}
.hoverable:hover:before, .hoverable:active:before, .hoverable:focus:before{
opacity: 1;
transform: translateY(-5px);
}



@keyframes bounce-animation {
16.65% {
  -webkit-transform: translateY(8px);
  transform: translateY(8px);
}

33.3% {
  -webkit-transform: translateY(-6px);
  transform: translateY(-6px);
}

49.95% {
  -webkit-transform: translateY(4px);
  transform: translateY(4px);
}

66.6% {
  -webkit-transform: translateY(-2px);
  transform: translateY(-2px);
}

83.25% {
  -webkit-transform: translateY(1px);
  transform: translateY(1px);
}

100% {
  -webkit-transform: translateY(0);
  transform: translateY(0);
}
}

.bounce {
animation-name: bounce-animation;
animation-duration: 5s;
}



/*everything below here is just setting up the page, so dont worry about it */


@media (min-width: 768px) {
.navbar{
  text-align: center !important;
  float: none;
  display: inline-block;
 
}
}

nav {
background: none !important;
text-transform:uppercase;
li {
  margin-left: 3em;
  margin-right: 3em;
  a{
    transition: .5s color ease-in-out;
  }
}
}

.page-title {
opacity: .75 !important;
}

</style>
<body style="background-color: wheat;"
  <div class="container-fluid">
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <ul class="nav navbar-nav">
          <li><a id="len1" class="hoverable" href="/">Home</a></li>
          <li><a id="len2" class="hoverable" href="#">About</a></li>
          <li><a id="len3" class="hoverable" href="{% url 'account:profile' %}">Profile</a></li>
        
        </ul>
      </div>
    </nav>
  </div>

  <br>

	<div>
		<button accesskey="p" id=play></button> &nbsp;
		<button accesskey="q" id=pause></button> &nbsp;
		<button id=stop></button>
	</div>
	<article>
    <h1 style="color: red;">INSTRUCTIONS TO THE CANDIDATES</h1>
    <h2></h2>
    <p>1 TOTAL QUESTIONS : 5</p>
    <p>2 TOTAL MARKS : 50 </p>
    <p>3 EXAM STARTING TIME : 11:00</p>
    <p>4 EXAM ENDING TIME : 1:00</p>
    <p>5 EACH QUESTION CARRY 10 MARKS</p>

    <p>6 TO START THE EXAM PLEASE PRESS 'A' </p>
    <p>7 ANSWERS WILL BE AUTOMATICALLY SUBMITTED ONCE THE TIME GETS OVER </p>
    <p>8 AFTER COMPLETING ANSWERING PLEASE PRESS 'S' .</p>
    <p>9 TO START THE EXAM PLEASE PRESS 'N' </p>
  </article>
  <center>
  <a href="{% url 'exam:startexam' %}">
    <button accesskey="n" id="myBtn" type="submit" class="btn btn-danger" style="width: 500px;margin-top: 175px;">Ok,Then Continue</button>
  </a>
</center>
</body>
<script>
onload = function() {
    if ('speechSynthesis' in window) with(speechSynthesis) {


        var playEle = document.querySelector('#play');
        var pauseEle = document.querySelector('#pause');
        var stopEle = document.querySelector('#stop');
        var flag = false;


        playEle.addEventListener('click', onClickPlay);
        pauseEle.addEventListener('click', onClickPause);
        stopEle.addEventListener('click', onClickStop);

        function onClickPlay() {
            if(!flag){
                flag = true;
                utterance = new SpeechSynthesisUtterance(document.querySelector('article').textContent);
                utterance.voice = getVoices()[0];
                utterance.onend = function(){
                    flag = false; playEle.className = pauseEle.className = ''; stopEle.className = 'stopped';
                };
                playEle.className = 'played';
                stopEle.className = '';
                speak(utterance);
            }
             if (paused) { /* unpause/resume narration */
                playEle.className = 'played';
                pauseEle.className = '';
                resume();
            } 
        }

        function onClickPause() {
            if(speaking && !paused){ /* pause narration */
                pauseEle.className = 'paused';
                playEle.className = '';
                pause();
            }
        }

        function onClickStop() {
            if(speaking){ /* stop narration */
                /* for safari */
                stopEle.className = 'stopped';
                playEle.className = pauseEle.className = '';
                flag = false;
                cancel();

            }
        }

    }

    else { /* speech synthesis not supported */
        msg = document.createElement('h5');
        msg.textContent = "Detected no support for Speech Synthesis";
        msg.style.textAlign = 'center';
        msg.style.backgroundColor = 'red';
        msg.style.color = 'white';
        msg.style.marginTop = msg.style.marginBottom = 0;
        document.body.insertBefore(msg, document.querySelector('div'));
    }

}

</script
</html>

templates/index2.html
<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->

<!DOCTYPE html>
{% load static %}
<html>
<head>

<meta name="viewport" content="width=device-width, initial-scale=1">
<meta charset="utf-8">
<meta name="keywords" content="Lyceum a Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, 
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
<link href='{% static "css/bootstrap.min.css" %}' rel="stylesheet" type="text/css" media="all">
<link href='{% static "css/fontawesome-all.min.css" %}' rel="stylesheet" type="text/css" media="all">
<link rel="stylesheet" href='{% static "css/flexslider.css" %}' type="text/css" media="all" />
<link href='{% static "css/easy-responsive-tabs.css" %}' rel='stylesheet' type='text/css'/>
<link href='{% static "css/smoothbox.css" %}' rel='stylesheet' type='text/css'/>
<link href='{% static "css/style.css" %}' rel="stylesheet" type="text/css" media="all"/>
<link href="//fonts.googleapis.com/css?family=Roboto:400,500,700,900" rel="stylesheet">
<link href="//fonts.googleapis.com/css?family=Open+Sans:400,600,700,800" rel="stylesheet">
<style>
  * {box-sizing: border-box;}

  body {
    margin: 0;
    font-family: Arial, Helvetica, sans-serif;
  }
  
  .topnav {
    overflow: hidden;
    background-color: #e9e9e9;
  }
  
  .topnav a {
    float: left;
    display: block;
    color: black;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
    font-size: 17px;
  }
  
  .topnav a:hover {
    background-color: #ddd;
    color: black;
  }
  
  .topnav a.active {
    background-color: #2196F3;
    color: white;
  }
  
  .topnav .search-container {
    float: right;
  }
  
  .topnav input[type=text] {
    padding: 6px;
    margin-top: 8px;
    font-size: 17px;
    border: none;
  }
  
  .topnav .search-container button {
    float: right;
    padding: 6px;
    margin-top: 8px;
    margin-right: 16px;
    background: #ddd;
    font-size: 17px;
    border: none;
    cursor: pointer;
  }
  
  .topnav .search-container button:hover {
    background: #ccc;
  }
 
  
  @media screen and (max-width: 600px) {
    .topnav .search-container {
      float: none;
    }
    .topnav a, .topnav input[type=text], .topnav .search-container button {
      float: none;
      display: block;
      text-align: left;
      width: 100%;
      margin: 0;
      padding: 14px;
    }
    .topnav input[type=text] {
      border: 1px solid #ccc;  
    }
  }
</style>
</head>
<body>

<!-- Header -->
<section class="header">
<div class="banner">
<div class="w3_banner">
<div class="container-fluid">
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="">
							<h1>Drishti</h1><label></label>
            </a><br>
        

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item ">
        <a class="nav-link" href="/">HOME </a>
      </li>
      <li class="nav-item">
        <a class="nav-link scroll" href="{% url 'exam:about' %}">ABOUT</a>
      </li>
      <li class="nav-item">
        <a class="nav-link scroll" href="{% url 'account:authlogin' %}"><b>AUTHORITY</b></a>
      </li>
      <li class="nav-item">
        <form method="GET" action="{% url 'exam:finalresult' %}">
          <span><input type="text" autocomplete="off" placeholder="Check Your Result...." style="background-color:rgb(167, 197, 174)"  name="q">
          <input type="submit" value="SEARCH " style="background-color:rgb(24, 173, 24);color:white"></span><br>
          <p style="color:red;"><b>* Enter Your Register Number </b></p>
        </form>
      </li>



      </li>
      
	
    </ul>

  </div>
</nav>


 
  <form>
    <center>
    <a href ="{% url 'account:login' %}">
      <button type="button" class="btn btn-success" style="width: 200px;margin-top: 145px;"><b>GET STARTED</b></button></a>
      </center>
  </form>

</div>
</div>

</div>
</section>
<!-- /Header -->

<!-- About -->



</body>
</html>

templates/questionslist.html


{% load static %}
<!DOCTYPE html>
<html>
<title>questionlist</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<style>
  .previous {
    background-color: rgb(255, 81, 0);
    color: black;
  }
  
.round {
  border-radius: 50%;
}
a {
  text-decoration: none;
  display: inline-block;
  padding: 8px 16px;
}

</style>
<p></p>
<a href="{% url 'account:adminduty' %}" class="previous round" style="margin-left: 1400px;">&#8249;</a>
<body style="background-color: cadetblue;">
    <h2><b><center>Questions</center></b></h2>
<div class="w3-container">
    {% for i in questionlist %}
  <h2></h2>
<div style="background-color:white">
  <ul class="w3-ul w3-card-4">
    <li class="w3-bar">
      <span onclick="this.parentElement.style.display='none'" class="w3-bar-item w3-button w3-white w3-xlarge w3-right">×</span>
      <img src="{% static 'images/question.png' %}" class="w3-bar-item w3-circle w3-hide-small" style="width:85px">
      <div class="w3-bar-item">
        <span class="w3-large"><b>{{i.question}}</b></span><br>
        
      </div>

      </div>
    </li>


    
  </ul>
  {% endfor %}
</div>

</body>
</html>


templates/resulttable.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
table {
  border-collapse: collapse;
  border-spacing: 0;
  width: 50%;
  border: 1px solid #ddd;
  margin-top: 60px;
  margin-left: 360px;
  
}

.previous {
    background-color: rgb(255, 81, 0);
    color: black;
  }
  
.round {
  border-radius: 50%;
}
a {
  text-decoration: none;
  display: inline-block;
  padding: 8px 16px;
}

th, td {
  text-align: center;
  padding: 8px;
}

tr:nth-child(even){background-color: #f2f2f2}
</style>
</head>
<body style="background-color: cadetblue;">
    <a href="/" style="color:#454b53;text-decoration: none">
      <h1 style="border: 4px solid white;width:200px;padding:4px;color:white">D r i s h t i</h1>
        </a>
        <a href="{% url 'account:adminduty' %}" class="previous round" style="margin-left: 1200px;">&#8249;</a>
  
   <center>
    <div class="container" style="margin-left: 250px;">
   <form method="POST">
    {% csrf_token %}
    <span>
    <div class="col-xs-3" >
      <input type="text" class="form-control" id="usr" name="n1" placeholder="Enter Student Name">
    </div>
    <div class="col-xs-3">
  
      <input type="text" class="form-control" id="pwd" name="q" placeholder="Enter Student Register Number">
    </div>
    <div class="col-xs-3">
    <input type="submit" value="SUBMIT" class="form-control" style="background-color: coral;color:ghostwhite"/>
  </div>
</span>
    <p>* Click <b>Submit</b>  to Find Total Mark</p>
   </center>
  </form>
</div>
  

<div style="overflow-x:auto;">

    <table style="background-color:rgb(201, 193, 193);">
        <tr>
            <th>NAME</th>
    
            <th>REGISTRATION NUMBER</th>

            <th>TOTAL MARKS</th>
        </tr>
        {% for item in finalscore %}
        <tr> 
            <td>{{ item.name }}</td>
        
            <td>{{ item.registration_number }}</td>

            <td>{{ item.totalmarks }}</td>
        </tr>
        {% endfor %}
    </table>

</div>

</body>
{% if message %}
<script>
 
  alert('{{ message }}');
</script>
{% endif %}
</html>